[package]
name = "grocery-pricing"
version = "0.1.0"
authors = ["Chris McKenzie <chris.mckenzie@tpfs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
